1708154777850	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1708157006224	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1708157006224	Sync.Service	DEBUG	User-Agent: Firefox/122.0.1 (Linux x86_64) FxSync/1.124.0.20240206142439.desktop
1708157006224	Sync.Service	INFO	Starting sync at 2024-02-17 08:03:26 in browser session J1UDb1qaEa-C
1708157006224	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1708157006227	Sync.Status	INFO	Resetting Status.
1708157006227	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1708157006228	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1708157006228	FirefoxAccounts	DEBUG	getOAuthToken enter
1708157006229	FirefoxAccounts	TRACE	getCachedToken returning cached token
1708157006229	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1708157006230	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1708157026469	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1708157026469	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1708157026471	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1708157026477	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1708157026534	Sync.SyncScheduler	DEBUG	Woke from sleep.
1708157026534	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1708157026534	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1708157026536	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1708157026539	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2147500036 - NS_ERROR_ABORT
1708157026539	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1708157028551	Sync.Service	DEBUG	User-Agent: Firefox/122.0.1 (Linux x86_64) FxSync/1.124.0.20240206142439.desktop
1708157028551	Sync.Service	INFO	Starting sync at 2024-02-17 08:03:48 in browser session J1UDb1qaEa-C
1708157028552	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1708157028552	Sync.Service	INFO	Cannot start sync: already syncing?
1708157029112	Sync.Service	DEBUG	User-Agent: Firefox/122.0.1 (Linux x86_64) FxSync/1.124.0.20240206142439.desktop
1708157029112	Sync.Service	INFO	Starting sync at 2024-02-17 08:03:49 in browser session J1UDb1qaEa-C
1708157029112	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1708157029112	Sync.Service	INFO	Cannot start sync: already syncing?
1708157029278	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1708157029278	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1708157029279	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1708157029280	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
