1715034686037	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1715034779031	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1715034779031	Sync.Service	DEBUG	User-Agent: Firefox/125.0.3 (Linux x86_64) FxSync/1.127.0.20240503195641.desktop
1715034779031	Sync.Service	INFO	Starting sync at 2024-05-06 23:32:59 in browser session -RKgTfPwPCqE
1715034779031	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1715034779034	Sync.Status	INFO	Resetting Status.
1715034779034	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1715034779035	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1715121540406	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1715121540407	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1715121540419	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1715121540421	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1715121540611	Sync.SyncScheduler	DEBUG	Woke from sleep.
1715121540611	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1715121540611	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1715121540612	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1715121542613	Sync.Service	DEBUG	User-Agent: Firefox/125.0.3 (Linux x86_64) FxSync/1.127.0.20240503195641.desktop
1715121542613	FirefoxAccounts	INFO	Polling device commands.
1715121542613	Sync.Service	INFO	Starting sync at 2024-05-07 23:39:02 in browser session -RKgTfPwPCqE
1715121542613	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1715121542614	Sync.Service	INFO	Cannot start sync: already syncing?
1715121542615	Services.Common.RESTRequest	DEBUG	GET request to https://api.accounts.firefox.com/v1/account/device/commands?index=0
1715121542617	Services.Common.RESTRequest	DEBUG	GET https://api.accounts.firefox.com/v1/account/device/commands?index=0 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1715121542618	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_UNKNOWN_HOST"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.sys.mjs:478
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get status :: line 615"  data: no] Stack trace: get status()@resource://services-common/rest.sys.mjs:615
request()@resource://services-common/hawkclient.sys.mjs:230
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get statusText :: line 630"  data: no] Stack trace: get statusText()@resource://services-common/rest.sys.mjs:630
request()@resource://services-common/hawkclient.sys.mjs:238
1715121542618	Hawk	DEBUG	(Response) /account/device/commands?index=0: code: null - Status text: null
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get headers :: line 662"  data: no] Stack trace: get headers()@resource://services-common/rest.sys.mjs:662
_maybeNotifyBackoff()@resource://services-common/hawkclient.sys.mjs:307
request()@resource://services-common/hawkclient.sys.mjs:246
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get headers :: line 662"  data: no] Stack trace: get headers()@resource://services-common/rest.sys.mjs:662
_maybeNotifyBackoff()@resource://services-common/hawkclient.sys.mjs:307
request()@resource://services-common/hawkclient.sys.mjs:247
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get statusText :: line 630"  data: no] Stack trace: get statusText()@resource://services-common/rest.sys.mjs:630
_constructError()@resource://services-common/hawkclient.sys.mjs:113
request()@resource://services-common/hawkclient.sys.mjs:252
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get status :: line 615"  data: no] Stack trace: get status()@resource://services-common/rest.sys.mjs:615
_constructError()@resource://services-common/hawkclient.sys.mjs:114
request()@resource://services-common/hawkclient.sys.mjs:252
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get status :: line 615"  data: no] Stack trace: get status()@resource://services-common/rest.sys.mjs:615
_constructError()@resource://services-common/hawkclient.sys.mjs:115
request()@resource://services-common/hawkclient.sys.mjs:252
1715121542618	Services.Common.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.sys.mjs :: get headers :: line 662"  data: no] Stack trace: get headers()@resource://services-common/rest.sys.mjs:662
_constructError()@resource://services-common/hawkclient.sys.mjs:121
request()@resource://services-common/hawkclient.sys.mjs:252
1715121542618	FirefoxAccounts	ERROR	error GETing /account/device/commands?index=0: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]","message":null,"code":null,"errno":null}
1715121542618	Sync.SyncScheduler	ERROR	Fetching missed remote commands failed.: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]","message":null,"code":null,"errno":null}
1715121543226	Sync.Service	DEBUG	User-Agent: Firefox/125.0.3 (Linux x86_64) FxSync/1.127.0.20240503195641.desktop
1715121543226	Sync.Service	INFO	Starting sync at 2024-05-07 23:39:03 in browser session -RKgTfPwPCqE
1715121543226	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1715121543226	Sync.Service	INFO	Cannot start sync: already syncing?
1715121544519	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1715121544519	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1715121544520	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1715121544521	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1715121544522	Sync.Service	DEBUG	User-Agent: Firefox/125.0.3 (Linux x86_64) FxSync/1.127.0.20240503195641.desktop
1715121544522	Sync.Service	INFO	Starting sync at 2024-05-07 23:39:04 in browser session -RKgTfPwPCqE
1715121544522	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1715121544522	Sync.Service	INFO	Cannot start sync: already syncing?
1715121545074	FirefoxAccounts	TRACE	observed topic=push-message, data=https://celebforum.to/, subject=[xpconnect wrapped nsISupports]
1715121545975	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1715121547147	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1715121547147	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1715121547148	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1715121547150	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
